### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by JoeMulligan**
I accidentally did it 3 times, but I am learning a lot!

### CODE REVIEW

**Comment by timdmulligan** [comment]
Your folder structure is messy. `hello_world.py` itself should be in the `src/` folder itself, not in a folder called `hello_world.py`. Also, look into adding the `.pyproj `, `.sln`, and `.vs` files to the .gitignore.

**Comment by timdmulligan** [comment]
@JoeMulligan looks like all you left was the `.sln` file. All I want is the `.py` file 😭

**Comment by JoeMulligan** [comment]
How about now?

**Comment by timdmulligan** [comment]
Closer! Your file has the `.py` extension twice (`.py.py`).

Two small things: 
1) Try to be more descriptive with your commit messages
2) There's an extra blank line at the top of your script

**Review by timdmulligan — APPROVED** [review]

**Comment by timdmulligan** [comment]
LGTM!

**Pull request merged**
